#!/bin/bash

# Quick and dirty script to install hyprland
# This script is meant to run on a clean fresh system
#

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
	echo -e "yay was located, moving on.\n"
	yay -Suy
else
	echo -e "yay was not located, please install yay. Exiting script.\n"
	exit
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
	LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
	echo -e "The following has been added to $LOC.\n"
	echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
	echo -e "\n"
	echo -e "Restarting NetworkManager service...\n"
	sudo systemctl restart NetworkManager
	sleep 3
fi

### Install all of the above packages ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
	yay -S --noconfirm hyprland-git waybar-hyprland libdisplay-info-git \
		swaybg swaylock-effects wofi wlogout xdg-desktop-portal-hyprland-git \
		ttf-jetbrains-mono-nerd noto-fonts-emoji \
		polkit-gnome python-requests \
		swappy grim slurp pamixer brightnessctl gvfs \
		bluez bluez-utils lxappearance xfce4-settings \
		kitty mako thunar \
		dracula-gtk-theme dracula-icons-git

	# Start the bluetooth service
	echo -e "Starting the Bluetooth Service...\n"
	sudo systemctl enable --now bluetooth.service
	sleep 2

	# Clean out other portals
	echo -e "Cleaning out conflicting xdg portals...\n"
	yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
	echo -e "Copying config files...\n"
	cp -R hypr ~/.config/
	cp -R kitty ~/.config/
	cp -R mako ~/.config/
	cp -R waybar ~/.config/
	cp -R swaylock ~/.config/
	cp -R wofi ~/.config/

	# Set some files as exacutable
	chmod +x ~/.config/hypr/xdg-portal-hyprland
	chmod +x ~/.config/waybar/scripts/waybar-wttr.py
fi

### Script is done ###
echo -e "Script had completed.\n"
echo -e "You can start Hyprland by typing Hyprland (note the capital H).\n"
read -n1 -rep 'Would you like to start Hyprland now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
	exec Hyprland
else
	exit
fi
