#!/bin/bash

# Quick and dirty script to install hyprland
# This script is meant to run on a clean fresh system
#

# set some colors
CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"
INSTLOG="install.log"

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
	echo -e "$COK - yay was located, moving on."
	yay -Suy
else
	echo -e "$CWR - Yay was NOT located, please install yay. Exiting script.\n",
	exit
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
	LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
	echo -e "The following has been added to $LOC.\n"
	echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
	echo -e "\n"
	echo -e "Restarting NetworkManager service...\n"
	sudo systemctl restart NetworkManager
	sleep 3
fi

### Install all of the above packages ####
read -n1 -rep $'[\e[1;33mACTION\e[0m] - Would you like to install the packages? (y,n) ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
	#Stage 1
	echo -e "\n$CNT - Stage 1 - Installing main components, this may take a while..."
	yay -S --noconfirm --needed $(cat DEPENDENCIES_MAIN)

	#Stage 2
	echo -e "\n$CNT - Stage 2 - Installing additional tools and utilities, this may take a while..."
	yay -S --noconfirm --needed $(cat DEPENDENCIES_TOOLS)

	#Stage 3
	echo -e "\n$CNT - Stage 3 - Installing theme, this may take a while..."
	yay -S --noconfirm --needed $(cat DEPENDENCIES_THEME)

	# Clean out other portals
	echo -e "$CNT - Cleaning out conflicting xdg portals..."
	yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk

fi

### Copy Config Files ###
read -n1 -rep $'[\e[1;33mACTION\e[0m] - Would you like to copy config files? (y,n) ' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
	echo -e "$CNT - Copying config files...\n"
	cp -R hypr ~/.config/
	cp -R kitty ~/.config/
	cp -R mako ~/.config/
	cp -R waybar ~/.config/
	cp -R swaylock ~/.config/
	cp -R wofi ~/.config/

	# Set some files as exacutable
	chmod +x ~/.config/hypr/xdg-portal-kill
	chmod +x ~/.config/waybar/scripts/waybar-wttr.py
fi

### Script is done ###
echo -e "$CNT - Script had completed!\n"
echo -e "You can start Hyprland by typing Hyprland (note the capital H).\n"

#---END---
